FORMAT: 1A
HOST: https://app.pipefy.com

# Pipefy API

This is the Pipefy API documentation, here you will find the guide on how to get started with the API.

# GraphQL

GraphQL is a query language for APIs created by Facebook in 2012.

**Refs**:
* [facebook.github.io/graphql](http://facebook.github.io/graphql/)
* [graphql.org](http://graphql.org/)

Features:
* Send a GraphQL query to the API and get exactly what you need, nothing more and nothing less. GraphQL queries always return predictable results. 
* GraphQL queries access not just the properties of one resource but also smoothly follow references between them. While typical REST APIs require loading from multiple URLs, GraphQL APIs get all the data your app needs in a single request.

After authenticate to [Pipefy](https://app.pipefy.com/), you can explore the API through the web interface:

[app.pipefy.com/graphiql](https://app.pipefy.com/graphiql)
![GraphiQL](https://raw.githubusercontent.com/pipefy/graphql-api-doc/master/pipefy_graphiql.png?token=ABKZf10D3_5J8dtbHbVupQQ9XTfVqGFHks5YzKrWwA%3D%3D)

# Authentication (OAuth / JWT)

Most of requests will require the OAuth Token, that must be send in request header.

The personal OAuth Token is found at **User Settings** on [Pipefy](https://app.pipefy.com)

|HTTP Header      | Header Value              |
|-----------------|---------------------------|
|Content-Type     | _application/json_        |
|**Authorization**|_Bearer <your_oauth_token>_|



**Refs**:
* [OAuth 2](https://oauth.net/2/)
* [JWT](https://jwt.io/introduction/)


# GraphQL Root Queries 
* Me (User info)
* Organizations (**Optional** parameter: Organizations IDs)
* Organization (**Required** parameter: Organization ID)
* Pipes

## Me [/queries{?me}]

Get information about yourself.

- User:
    - ID
    - Name
    - Username
    - Avatar URL
    - Email
    - Locale
    - Timezone

**Request Body**

```
{ 
    query: { 
        me { id, name, username, avatar_url, email, locale, time_zone }
    }
}
```

### Get Me [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer your_oauth_token

    + Body

            { "query": "{ me { id, name, username, avatar_url, email, locale, time_zone } }" }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "data": {
                    "me": {
                        "id": 9999,
                        "name": "Pipefy User",
                        "username": "pipefy.user",
                        "avatar_url": "https://avatar-images.pipefy.com/user-avatar.png",
                        "email": "pipefy.user@pipefy.com",
                        "locale": "en-US",
                        "time_zone": "America/Los_Angeles"
                    }
                }
            }




## Organizations [/queries{?organizations}]

Get the list of Organizations.

- Organizations:
    - ID
    - Name

**Request Body**
```
{ 
    query: { 
        organizations { id, name } 
    }
}
```

### Get organizations [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer your_oauth_token

    + Body

            { "query": "{ organizations{ id, name} }" }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "data": {
                    "organizations": [
                        {
                            "id": "9999",
                            "name": "Pipefy"
                        }
                    ]
                }
            }
            
## Organization [/queries{?organization}]

Get an Organization by Organization ID, with Pipes and Phases.

- Organization:
    - Name
    - Pipes:
        - Name
        - Phases:
            - Name

**Request Body**
```
{ 
    query: { 
        organization(id: 9999) { 
            name
            pipes { 
                name
                phases { name } 
            } 
        } 
    } 
}
```

### Get organization by ID [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer your_oauth_token

    + Body

            { "query": "{ organization(id: 1){ name, pipes { name, phases { name } } } }" }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "data": {
                    "organization": {
                        "name": "Pipefy",
                        "pipes": [
                            {
                                "name": "Developers Team",
                                "phases": [
                                    {
                                        "name": "ToDo"
                                    },
                                    {
                                        "name": "Doing"
                                    },
                                    {
                                        "name": "Done"
                                    }
                                ]
                            },
                            {
                                "name": "Sales Team",
                                "phases": [
                                    {
                                        "name": "To-do"
                                    },
                                    {
                                        "name": "Doing"
                                    },
                                    {
                                        "name": "Done"
                                    }
                                ]
                            }
                        ]
                    }
                }
            }
   
## Pipes [/queries{?pipes}]

Get Pipes by Pipes IDs, with Phases and Cards.

- Pipes:
    - ID
    - Name
    - Phases:
        - Name
        - Cards ([Relay Connections specs](https://facebook.github.io/relay/docs/graphql-connections.html)):
            - Edges:
                - Node (Cards):
                    - ID (Card ID)
                    - Title (Card Title)
                


**Request Body**
```
{
    query: {
        pipes(ids: [1]){
            id
            name
            phases{
                name
                cards(first: 10){
                    edges{
                        node{
                            id
                            title
                        }
                    }
                }
            }
        }
    }
}
```

### Get Pipes by IDs [POST]

+ Request (application/json)

    + Headers

            Authorization: Bearer your_oauth_token

    + Body

            { "query": "{ pipes(ids: [1]){ id, name, phases{ name, cards(first: 10){ edges{ nodes{ id, title } } } } } }" }

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "data": {
                    "pipes": [
                        {
                            "id": "1",
                            "name": "Developers Team",
                            "phases": [
                                {
                                    "name": "To-Do",
                                    "cards": {
                                        "edges": [
                                            {
                                                "node": {
                                                    "id": "4",
                                                    "title": "Tuning API Cache"
                                                }
                                            },
                                            {
                                                "node": {
                                                    "id": "5",
                                                    "title": "Measure API Performance =D"
                                                }
                                            }
                                        ]
                                    }
                                },
                                {
                                    "name": "Doing",
                                    "cards": {
                                        "edges": [
                                            {   
                                                "node": {
                                                    "id": "3",
                                                    "title": "Create API Documentation ;-)"
                                                }
                                            }
                                        ]
                                    }
                                },
                                {
                                    "name": "Done",
                                    "cards": {
                                        "edges": [
                                            {
                                                "node": {
                                                    "id": "2",
                                                    "title": "Improve API"
                                                }
                                            },
                                            {
                                                "node": {
                                                    "id": "1",
                                                    "title": "Measure API Performance =/"
                                                }
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                }
            }